/* Delimiter changed to ; */
/* Connecting to localhost via MariaDB or MySQL (TCP/IP), username root, using password: No ... */
SELECT CONNECTION_ID();
SHOW VARIABLES;
/* Characterset: utf8mb4 */
SHOW /*!50002 GLOBAL */ STATUS;
SELECT NOW();
/* Connected. Thread-ID: 12 */
/* Reading function definitions from C:\Program Files\HeidiSQL\functions-mariadb.ini */
SHOW TABLES FROM `information_schema`;
SHOW DATABASES;
SHOW OPEN TABLES FROM mitrovski WHERE `in_use`!=0;
USE `mitrovski`;
/* Entering session "Unnamed" */
SELECT `DEFAULT_COLLATION_NAME` FROM `information_schema`.`SCHEMATA` WHERE `SCHEMA_NAME`='mitrovski';
SHOW TABLE STATUS FROM `mitrovski`;
SHOW FUNCTION STATUS WHERE `Db`='mitrovski';
SHOW PROCEDURE STATUS WHERE `Db`='mitrovski';
SHOW TRIGGERS FROM `mitrovski`;
SELECT *, EVENT_SCHEMA AS `Db`, EVENT_NAME AS `Name` FROM information_schema.`EVENTS` WHERE `EVENT_SCHEMA`='mitrovski';
/* Loading file "C:\Users\Mitrovski\OneDrive\Documents\Query.sql" (420 B) into query tab #1 ... */
/* Loading file "C:\Users\Mitrovski\OneDrive\Documents\Query #2.sql" (186 B) into query tab #2 ... */
/* Loading file "C:\Users\Mitrovski\OneDrive\Documents\Query.sql" (420 B) into query tab #3 ... */
/* Loading file "C:\Users\Mitrovski\OneDrive\Desktop\database backup\mitrovski_2022_11_20.sql" (5.5 KiB) into query tab #4 ... */
/* Scaling controls to screen DPI: 125% */
SELECT `DEFAULT_COLLATION_NAME` FROM `information_schema`.`SCHEMATA` WHERE `SCHEMA_NAME`='tanevska';
SHOW TABLE STATUS FROM `tanevska`;
SHOW FUNCTION STATUS WHERE `Db`='tanevska';
SHOW PROCEDURE STATUS WHERE `Db`='tanevska';
SHOW TRIGGERS FROM `tanevska`;
SELECT *, EVENT_SCHEMA AS `Db`, EVENT_NAME AS `Name` FROM information_schema.`EVENTS` WHERE `EVENT_SCHEMA`='tanevska';
USE `tanevska`;
SELECT * FROM `information_schema`.`COLUMNS` WHERE TABLE_SCHEMA='tanevska' AND TABLE_NAME='authors' ORDER BY ORDINAL_POSITION;
SHOW INDEXES FROM `authors` FROM `tanevska`;
SELECT * FROM information_schema.REFERENTIAL_CONSTRAINTS WHERE   CONSTRAINT_SCHEMA='tanevska'   AND TABLE_NAME='authors'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SELECT * FROM information_schema.KEY_COLUMN_USAGE WHERE   TABLE_SCHEMA='tanevska'   AND TABLE_NAME='authors'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SHOW ENGINES;
SHOW COLLATION;
SHOW CREATE TABLE `tanevska`.`authors`;
SELECT CONSTRAINT_NAME, CHECK_CLAUSE FROM `information_schema`.`CHECK_CONSTRAINTS` WHERE CONSTRAINT_SCHEMA='tanevska' AND TABLE_NAME='authors';
SELECT * FROM `tanevska`.`authors` LIMIT 1000;
SHOW CHARSET;
SELECT 'tanevska' AS `Database`, 'authors' AS `Table`, 11 AS `Rows`, 0 AS `Duration`;
/*!40101 SET @OLD_LOCAL_SQL_MODE=@@SQL_MODE, SQL_MODE='' */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
SHOW CREATE DATABASE `tanevska`;
SHOW CREATE TABLE `tanevska`.`authors`;
SELECT * FROM `tanevska`.`authors` LIMIT 64016;
SELECT 'tanevska' AS `Database`, 'books' AS `Table`, 12 AS `Rows`, 0 AS `Duration`;
SHOW CREATE DATABASE `tanevska`;
SHOW CREATE TABLE `tanevska`.`books`;
SELECT * FROM `tanevska`.`books` LIMIT 38409;
SELECT * FROM `information_schema`.`COLUMNS` WHERE TABLE_SCHEMA='tanevska' AND TABLE_NAME='books' ORDER BY ORDINAL_POSITION;
SHOW INDEXES FROM `books` FROM `tanevska`;
SELECT * FROM information_schema.REFERENTIAL_CONSTRAINTS WHERE   CONSTRAINT_SCHEMA='tanevska'   AND TABLE_NAME='books'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SELECT * FROM information_schema.KEY_COLUMN_USAGE WHERE   TABLE_SCHEMA='tanevska'   AND TABLE_NAME='books'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SELECT 'tanevska' AS `Database`, '_delete_authors' AS `Table`, -1 AS `Rows`, 0 AS `Duration`;
SHOW CREATE DATABASE `tanevska`;
SHOW CREATE PROCEDURE `tanevska`.`_delete_authors`;
SELECT 'tanevska' AS `Database`, '_delete_books' AS `Table`, -1 AS `Rows`, 0 AS `Duration`;
SHOW CREATE DATABASE `tanevska`;
SHOW CREATE PROCEDURE `tanevska`.`_delete_books`;
SELECT 'tanevska' AS `Database`, '_insert_authors' AS `Table`, -1 AS `Rows`, 0 AS `Duration`;
SHOW CREATE DATABASE `tanevska`;
SHOW CREATE PROCEDURE `tanevska`.`_insert_authors`;
SELECT 'tanevska' AS `Database`, '_insert_books' AS `Table`, -1 AS `Rows`, 0 AS `Duration`;
SHOW CREATE DATABASE `tanevska`;
SHOW CREATE PROCEDURE `tanevska`.`_insert_books`;
SELECT 'tanevska' AS `Database`, '_select_authors' AS `Table`, -1 AS `Rows`, 0 AS `Duration`;
SHOW CREATE DATABASE `tanevska`;
SHOW CREATE PROCEDURE `tanevska`.`_select_authors`;
SELECT 'tanevska' AS `Database`, '_select_authors_byCountry' AS `Table`, -1 AS `Rows`, 0 AS `Duration`;
SHOW CREATE DATABASE `tanevska`;
SHOW CREATE PROCEDURE `tanevska`.`_select_authors_byCountry`;
SELECT 'tanevska' AS `Database`, '_select_authors_germany' AS `Table`, -1 AS `Rows`, 0 AS `Duration`;
SHOW CREATE DATABASE `tanevska`;
SHOW CREATE PROCEDURE `tanevska`.`_select_authors_germany`;
SELECT 'tanevska' AS `Database`, '_select_books' AS `Table`, -1 AS `Rows`, 0 AS `Duration`;
SHOW CREATE DATABASE `tanevska`;
SHOW CREATE PROCEDURE `tanevska`.`_select_books`;
SELECT 'tanevska' AS `Database`, '_select_books_totalpageDESC' AS `Table`, -1 AS `Rows`, 0 AS `Duration`;
SHOW CREATE DATABASE `tanevska`;
SHOW CREATE PROCEDURE `tanevska`.`_select_books_totalpageDESC`;
SELECT 'tanevska' AS `Database`, '_select_genres' AS `Table`, -1 AS `Rows`, 0 AS `Duration`;
SHOW CREATE DATABASE `tanevska`;
SHOW CREATE PROCEDURE `tanevska`.`_select_genres`;
SELECT 'tanevska' AS `Database`, '_select_genres_param' AS `Table`, -1 AS `Rows`, 0 AS `Duration`;
SHOW CREATE DATABASE `tanevska`;
SHOW CREATE PROCEDURE `tanevska`.`_select_genres_param`;
SELECT 'tanevska' AS `Database`, '_select_inner_join' AS `Table`, -1 AS `Rows`, 0 AS `Duration`;
SHOW CREATE DATABASE `tanevska`;
SHOW CREATE PROCEDURE `tanevska`.`_select_inner_join`;
SELECT 'tanevska' AS `Database`, '_select_left_join' AS `Table`, -1 AS `Rows`, 0 AS `Duration`;
SHOW CREATE DATABASE `tanevska`;
SHOW CREATE PROCEDURE `tanevska`.`_select_left_join`;
SELECT 'tanevska' AS `Database`, '_select_right_join' AS `Table`, -1 AS `Rows`, 0 AS `Duration`;
SHOW CREATE DATABASE `tanevska`;
SHOW CREATE PROCEDURE `tanevska`.`_select_right_join`;
SELECT 'tanevska' AS `Database`, '_select_totalpagesASC' AS `Table`, -1 AS `Rows`, 0 AS `Duration`;
SHOW CREATE DATABASE `tanevska`;
SHOW CREATE PROCEDURE `tanevska`.`_select_totalpagesASC`;
SELECT 'tanevska' AS `Database`, '_update_authors' AS `Table`, -1 AS `Rows`, 0 AS `Duration`;
SHOW CREATE DATABASE `tanevska`;
SHOW CREATE PROCEDURE `tanevska`.`_update_authors`;
SELECT 'tanevska' AS `Database`, '_update_books' AS `Table`, -1 AS `Rows`, 0 AS `Duration`;
SHOW CREATE DATABASE `tanevska`;
SHOW CREATE PROCEDURE `tanevska`.`_update_books`;
/*!40101 SET SQL_MODE=IFNULL(@OLD_LOCAL_SQL_MODE, '') */;
/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
SELECT CONSTRAINT_NAME, CHECK_CLAUSE FROM `information_schema`.`CHECK_CONSTRAINTS` WHERE CONSTRAINT_SCHEMA='tanevska' AND TABLE_NAME='books';
SELECT * FROM `tanevska`.`books` LIMIT 1000;
SHOW VARIABLES;
SHOW CREATE DATABASE `tanevska`;
SHOW DATABASES;
/* Entering session "Unnamed" */
USE `mitrovski`;
SELECT `DEFAULT_COLLATION_NAME` FROM `information_schema`.`SCHEMATA` WHERE `SCHEMA_NAME`='mitrovski';
SHOW TABLE STATUS FROM `mitrovski`;
SHOW FUNCTION STATUS WHERE `Db`='mitrovski';
SHOW PROCEDURE STATUS WHERE `Db`='mitrovski';
SHOW TRIGGERS FROM `mitrovski`;
SELECT *, EVENT_SCHEMA AS `Db`, EVENT_NAME AS `Name` FROM information_schema.`EVENTS` WHERE `EVENT_SCHEMA`='mitrovski';
USE `tanevska`;
SELECT `DEFAULT_COLLATION_NAME` FROM `information_schema`.`SCHEMATA` WHERE `SCHEMA_NAME`='tanevska';
SHOW TABLE STATUS FROM `tanevska`;
SHOW FUNCTION STATUS WHERE `Db`='tanevska';
SHOW PROCEDURE STATUS WHERE `Db`='tanevska';
SHOW TRIGGERS FROM `tanevska`;
SELECT *, EVENT_SCHEMA AS `Db`, EVENT_NAME AS `Name` FROM information_schema.`EVENTS` WHERE `EVENT_SCHEMA`='tanevska';
SELECT CURRENT_USER();
SHOW CREATE PROCEDURE `tanevska`.`_delete_authors`;
SELECT CURRENT_USER();
SHOW CREATE PROCEDURE `tanevska`.`_delete_books`;
SELECT CURRENT_USER();
SHOW CREATE PROCEDURE `tanevska`.`_insert_authors`;
SELECT CURRENT_USER();
SHOW CREATE PROCEDURE `tanevska`.`_select_authors`;
SELECT CURRENT_USER();
SHOW CREATE PROCEDURE `tanevska`.`_select_authors_byCountry`;
SELECT * FROM `information_schema`.`COLUMNS` WHERE TABLE_SCHEMA='tanevska' AND TABLE_NAME='authors' ORDER BY ORDINAL_POSITION;
SELECT `DEFAULT_COLLATION_NAME` FROM `information_schema`.`SCHEMATA` WHERE `SCHEMA_NAME`='test';
SHOW TABLE STATUS FROM `test`;
SHOW FUNCTION STATUS WHERE `Db`='test';
SHOW PROCEDURE STATUS WHERE `Db`='test';
SHOW TRIGGERS FROM `test`;
SELECT *, EVENT_SCHEMA AS `Db`, EVENT_NAME AS `Name` FROM information_schema.`EVENTS` WHERE `EVENT_SCHEMA`='test';
SELECT 'tanevska' AS `Database`, 'authors' AS `Table`, 10 AS `Rows`, 0 AS `Duration`;
/*!40101 SET @OLD_LOCAL_SQL_MODE=@@SQL_MODE, SQL_MODE='' */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
SHOW CREATE DATABASE `tanevska`;
SHOW CREATE TABLE `tanevska`.`authors`;
SELECT * FROM `tanevska`.`authors` LIMIT 64016;
SELECT * FROM `information_schema`.`COLUMNS` WHERE TABLE_SCHEMA='tanevska' AND TABLE_NAME='authors' ORDER BY ORDINAL_POSITION;
SHOW INDEXES FROM `authors` FROM `tanevska`;
SELECT * FROM information_schema.REFERENTIAL_CONSTRAINTS WHERE   CONSTRAINT_SCHEMA='tanevska'   AND TABLE_NAME='authors'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SELECT * FROM information_schema.KEY_COLUMN_USAGE WHERE   TABLE_SCHEMA='tanevska'   AND TABLE_NAME='authors'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SELECT 'tanevska' AS `Database`, 'books' AS `Table`, 12 AS `Rows`, 0 AS `Duration`;
SHOW CREATE DATABASE `tanevska`;
SHOW CREATE TABLE `tanevska`.`books`;
SELECT * FROM `tanevska`.`books` LIMIT 38409;
SELECT * FROM `information_schema`.`COLUMNS` WHERE TABLE_SCHEMA='tanevska' AND TABLE_NAME='books' ORDER BY ORDINAL_POSITION;
SHOW INDEXES FROM `books` FROM `tanevska`;
SELECT * FROM information_schema.REFERENTIAL_CONSTRAINTS WHERE   CONSTRAINT_SCHEMA='tanevska'   AND TABLE_NAME='books'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SELECT * FROM information_schema.KEY_COLUMN_USAGE WHERE   TABLE_SCHEMA='tanevska'   AND TABLE_NAME='books'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SELECT 'tanevska' AS `Database`, '_delete_authors' AS `Table`, -1 AS `Rows`, 0 AS `Duration`;
SHOW CREATE DATABASE `tanevska`;
SHOW CREATE PROCEDURE `tanevska`.`_delete_authors`;
SELECT 'tanevska' AS `Database`, '_delete_books' AS `Table`, -1 AS `Rows`, 0 AS `Duration`;
SHOW CREATE DATABASE `tanevska`;
SHOW CREATE PROCEDURE `tanevska`.`_delete_books`;
SELECT 'tanevska' AS `Database`, '_insert_authors' AS `Table`, -1 AS `Rows`, 0 AS `Duration`;
SHOW CREATE DATABASE `tanevska`;
SHOW CREATE PROCEDURE `tanevska`.`_insert_authors`;
SELECT 'tanevska' AS `Database`, '_insert_books' AS `Table`, -1 AS `Rows`, 0 AS `Duration`;
SHOW CREATE DATABASE `tanevska`;
SHOW CREATE PROCEDURE `tanevska`.`_insert_books`;
SELECT 'tanevska' AS `Database`, '_select_authors' AS `Table`, -1 AS `Rows`, 0 AS `Duration`;
SHOW CREATE DATABASE `tanevska`;
SHOW CREATE PROCEDURE `tanevska`.`_select_authors`;
SELECT 'tanevska' AS `Database`, '_select_authors_byCountry' AS `Table`, -1 AS `Rows`, 0 AS `Duration`;
SHOW CREATE DATABASE `tanevska`;
SHOW CREATE PROCEDURE `tanevska`.`_select_authors_byCountry`;
SELECT 'tanevska' AS `Database`, '_select_authors_germany' AS `Table`, -1 AS `Rows`, 0 AS `Duration`;
SHOW CREATE DATABASE `tanevska`;
SHOW CREATE PROCEDURE `tanevska`.`_select_authors_germany`;
SELECT 'tanevska' AS `Database`, '_select_books' AS `Table`, -1 AS `Rows`, 0 AS `Duration`;
SHOW CREATE DATABASE `tanevska`;
SHOW CREATE PROCEDURE `tanevska`.`_select_books`;
SELECT 'tanevska' AS `Database`, '_select_books_totalpageDESC' AS `Table`, -1 AS `Rows`, 0 AS `Duration`;
SHOW CREATE DATABASE `tanevska`;
SHOW CREATE PROCEDURE `tanevska`.`_select_books_totalpageDESC`;
SELECT 'tanevska' AS `Database`, '_select_genres' AS `Table`, -1 AS `Rows`, 0 AS `Duration`;
SHOW CREATE DATABASE `tanevska`;
SHOW CREATE PROCEDURE `tanevska`.`_select_genres`;
SELECT 'tanevska' AS `Database`, '_select_genres_param' AS `Table`, -1 AS `Rows`, 0 AS `Duration`;
SHOW CREATE DATABASE `tanevska`;
SHOW CREATE PROCEDURE `tanevska`.`_select_genres_param`;
SELECT 'tanevska' AS `Database`, '_select_inner_join' AS `Table`, -1 AS `Rows`, 0 AS `Duration`;
SHOW CREATE DATABASE `tanevska`;
SHOW CREATE PROCEDURE `tanevska`.`_select_inner_join`;
SELECT 'tanevska' AS `Database`, '_select_left_join' AS `Table`, -1 AS `Rows`, 0 AS `Duration`;
SHOW CREATE DATABASE `tanevska`;
SHOW CREATE PROCEDURE `tanevska`.`_select_left_join`;
SELECT 'tanevska' AS `Database`, '_select_right_join' AS `Table`, -1 AS `Rows`, 0 AS `Duration`;
SHOW CREATE DATABASE `tanevska`;
SHOW CREATE PROCEDURE `tanevska`.`_select_right_join`;
SELECT 'tanevska' AS `Database`, '_select_totalpagesASC' AS `Table`, -1 AS `Rows`, 0 AS `Duration`;
SHOW CREATE DATABASE `tanevska`;
SHOW CREATE PROCEDURE `tanevska`.`_select_totalpagesASC`;
SELECT 'tanevska' AS `Database`, '_update_authors' AS `Table`, -1 AS `Rows`, 0 AS `Duration`;
SHOW CREATE DATABASE `tanevska`;
SHOW CREATE PROCEDURE `tanevska`.`_update_authors`;
SELECT 'tanevska' AS `Database`, '_update_books' AS `Table`, -1 AS `Rows`, 0 AS `Duration`;
SHOW CREATE DATABASE `tanevska`;
SHOW CREATE PROCEDURE `tanevska`.`_update_books`;
/*!40101 SET SQL_MODE=IFNULL(@OLD_LOCAL_SQL_MODE, '') */;
/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;